### ISSUE TITLE
Upload Failure 

### ISSUE THREAD

**Issue by nabobalis** [conda-forge/sunpy-feedstock#27]
We are in the process of a new major package release and discovered that the uploads failed. As per this issue [here.](https://github.com/conda-forge/conda-forge.github.io/issues/426)

Is there any chance we can get this issue resolved quickly? 

Ping @mwcraig and @conda-forge/core

**Comment by Cadair** [comment]
The recipie had been readded, so hopefully this will now upload.

**Comment by mwcraig** [comment]
It will take a while for the re-render to happen....

**Comment by Cadair** [comment]
Thanks for the help @mwcraig
