### ISSUE TITLE
Update runtime deps to avoid errors when we ask users to run self_test

### ISSUE THREAD

**Issue by nabobalis** [conda-forge/sunpy-feedstock#55]
See: https://github.com/sunpy/sunpy/issues/3467

Should be done for 1.0 and the incoming 1.1 recipes. 

It is probably time for a sunpy-base and a sunpy package for conda forge. 
See: https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml 
for an example.

**Comment by Cadair** [comment]
I think I would rather have our test suite fail with "you need to install test dependencies" than add even more deps to our conda package. We should think about the tradeoffs here.

**Comment by nabobalis** [comment]
What is the trade offs?
